import{a as q,S as P,i}from"./assets/vendor-S2qh7U4E.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const B="56853055-640f52739347c513669db01a2",M="https://pixabay.com/api/",g=async(o,t=1)=>(await q.get(M,{params:{key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data,p=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more");let R=new P(".gallery a",{captionsData:"alt",captionDelay:250});const f=o=>{const t=o.map(({webformatURL:s,largeImageURL:l,tags:e,likes:r,views:n,comments:S,downloads:v})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${l}">
        <img class="gallery-image" src="${s}" alt="${e}" />
        <div class="info">
          <p class="info-item"><b>Likes</b> ${r}</p>
          <p class="info-item"><b>Views</b> ${n}</p>
          <p class="info-item"><b>Comments</b> ${S}</p>
          <p class="info-item"><b>Downloads</b> ${v}</p>
        </div>
      </a>
    </li>
  `).join("");p.insertAdjacentHTML("beforeend",t),R.refresh()},$=()=>{p.innerHTML=""},b=()=>{h.classList.remove("is-hidden")},L=()=>{h.classList.add("is-hidden")},w=()=>{y.classList.remove("is-hidden")},d=()=>{y.classList.add("is-hidden")},m=document.querySelector(".form"),E=document.querySelector(".load-more");let c="",a=1,u=0;m.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.currentTarget.elements["search-text"].value.trim(),!c){i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}a=1,$(),d(),b();try{const t=await g(c,a);if(t.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}u=Math.ceil(t.totalHits/15),f(t.hits),a<u?w():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){console.error(t),i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L(),m.reset()}});E.addEventListener("click",async()=>{a+=1,d(),b();try{const o=await g(c,a);f(o.hits);const t=document.querySelector(".gallery-item");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}a>=u?(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch(o){console.error(o),i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
